version: '3'
services:
  order:
    build:
        context: .
        dockerfile: Dockerfile
    image: order
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fu-capstone-order
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:latest
    # ports:
    #   - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: fu-capstone-order
    volumes:
      - ./db-data:/var/lib/postgresql/data