apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db-deployment # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: order-db-container
        image: postgres # Sets Image
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432 # Exposes container port
        # envFrom:
        #   - configMapRef:
        #       name: postgres-config
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "1"
        - name: POSTGRES_DB
          value: fu-capstone-order
      #   volumeMounts:
      #     - mountPath: /var/lib/postgresql/data
      #       name: postgres-data
      # volumes:
      #   - name: postgres-data
      #     persistentVolumeClaim:
      #       claimName: order-db-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: order-db # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  selector:
    app: postgres
  ports:
    - port: 5433 # Sets port to run the postgres application
      targetPort: 5432
  type: ClusterIP # Sets service type 
