---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: inventory-db-manual
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-db-pv-claim
  labels:
    app: inventory-db-postgres
spec:
  storageClassName: inventory-db-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: order-db-manual
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: order-db-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: product-db-manual
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-db-pvc
  labels:
    app: product-db-mongo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: product-db-manual
  resources:
    requests:
      storage: 1Gi

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: review-db-manual
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: review-db-pv-claim
  labels:
    app: review-db-mongo
spec:
  storageClassName: review-db-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shopping-db-manual
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopping-db-pv-claim
  labels:
    app: shopping-db-mongo
spec:
  storageClassName: shopping-db-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: user-db-manual
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: user-db-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi