apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-service-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-service-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order-service-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-service-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-service-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-service-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: review-service-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: review-service-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shopping-service-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopping-service-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50