apiVersion: v1
kind: PersistentVolume
metadata:
  name: inventory-db-pv
  labels:
    type: local
    app: inventory-db-postgres
spec:
  storageClassName: inventory-db-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/inventory-db-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-db-pv-claim
  labels:
    app: inventory-db-postgres
spec:
  storageClassName: inventory-db-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



