apiVersion: apps/v1
kind: Deployment
metadata: 
  name: inventory-service-deployment
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: inventory-service
  template: 
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory
          image: docker.io/doanhthuc/inventory-service
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3002
          command: ["/bin/sh","-c"]
          args: ["yarn typeorm migration:run -d ./src/data-source.ts && yarn start"]
          env:
          - name: NODE_ENV
            value: production
          - name: DATABASE_URL
            value: postgres://postgres:1@inventory-db:5432/fu-capstone-inventory
---
apiVersion: v1
kind: Service
metadata: 
  name: inventory-service
spec: 
  selector:
    app: inventory-service
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP