apiVersion: v1
kind: PersistentVolume
metadata:
  name: review-db-pv
  labels:
    type: local
    app: review-db-mongo
spec:
  storageClassName: review-db-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/review-db-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: review-db-pv-claim
  labels:
    app: review-db-mongo
spec:
  storageClassName: review-db-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



