version: '3'
services:
  product:
    build: 
      context: .
      dockerfile: Dockerfile
    image: product
    # container_name: product
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      NODE_ENV: production
      # DATABASE_URL: postgres://postgres:1@postgres:5432/fu-capstone-inventory
    # working_dir: /usr/src/app
    # command: sh -c "yarn start"
