version: '3'
services:
  product:
    build: 
      context: .
      dockerfile: Dockerfile
    image: product
    container_name: product-service
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      NODE_ENV: production
      MONGO_URI: mongodb://product-db:27017/
      MONGO_INITDB_DATABASE: fu-capstone-product
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    depends_on:
      - product-db
  product-db:
    image: mongo
    container_name: product-mongo-db
    # ports: 
    #   - '27017:27017'
    environment: 
      MONGO_INITDB_DATABASE: fu-capstone-product
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    # enable auth for mongo
    command: --auth 
    volumes:
      - product-mongo-data:/data/db
volumes:
  product-mongo-data:
