kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: product-db-manual
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-db-pvc
  labels:
    app: product-db-mongo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: product-db-manual
  resources:
    requests:
      storage: 1Gi










# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: slow
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp2
# reclaimPolicy: Retain
# # ---
# # apiVersion: v1
# # kind: PersistentVolume
# # metadata:
# #   name: product-db-pv
# #   # labels:
# #     # type: local
# #     # app: product-db-mongo
# # spec:
# #   storageClassName: slow
# #   # storageClassName: product-db-manual
# #   capacity:
# #     storage: 1Gi
# #   accessModes:
# #     - ReadWriteMany
# #   # hostPath:
# #   #   path: "/mnt/data/product-db-pv"
# #   awsElasticBlockStore:
# #     volumeID: "vol-0c17842c9dea26017"
# #     fsType: ext4
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: product-db-pv
# spec:
#   storageClassName: slow
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   awsElasticBlockStore:
#     volumeID: "vol-0c17842c9dea26017"
#     fsType: ext4
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: product-db-pv-claim
#   # labels:
#   #   app: product-db-mongo
# spec:
#   storageClassName: slow
#   # storageClassName: product-db-manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
