apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-db-pv
  labels:
    type: local
    app: postgres
    # storage-class: user-db-manual
spec:
  storageClassName: user-db-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/user-db-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: user-db-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



